module.exports.userService=require('./user.service')
module.exports.emailService=require('./email.service')
module.exports.tokenService=require('./token.service')
module.exports.productService=require('./product.service')
module.exports.categoryService=require('./category.service')
module.exports.subCategoryService=require('./subCategory.service')
module.exports.childSubCategoryService=require('./childSubCategory.service')