module.exports.userController=require('./user.controller')
module.exports.productController=require('./product.controller')
module.exports.categoryController=require('./category.controller')
module.exports.subCategoryController=require('./subCategory.controller')
module.exports.childSubCategoryController=require('./childSubCategory.controller')
module.exports.productImagesController=require('./productImages.controller')
module.exports.cartController=require('./cart.controller')
module.exports.tokenController=require('./token.controller')